theme: jekyll-theme-minimal
logo: "https://media.discordapp.net/attachments/855806170966261791/875945924285853756/lel.png?width=702&height=702"
title: "Github-Pages-Demo-Theme"
url: "https://kadedevteam.github.io/Github-Website-Demo/"
